# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(402, 300)
        self.na_Label = QtWidgets.QLabel(Form)
        self.na_Label.setGeometry(QtCore.QRect(51, 70, 101, 31))
        self.na_Label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.na_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 85, 0);\n"
"font: 10pt \"楷体\";")
        self.na_Label.setTextFormat(QtCore.Qt.AutoText)
        self.na_Label.setObjectName("na_Label")
        self.pw_Label = QtWidgets.QLabel(Form)
        self.pw_Label.setGeometry(QtCore.QRect(51, 154, 101, 31))
        self.pw_Label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"background-color: rgb(170, 85, 0);\n"
"font: 10pt \"楷体\";")
        self.pw_Label.setObjectName("pw_Label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(180, 70, 151, 31))
        self.lineEdit.setStyleSheet("font: 10pt \"黑体\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 150, 151, 31))
        self.lineEdit_2.setStyleSheet("font: 10pt \"黑体\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lg_Button = QtWidgets.QPushButton(Form)
        self.lg_Button.setGeometry(QtCore.QRect(70, 220, 111, 41))
        self.lg_Button.setStyleSheet("font: 12pt \"方正粗黑宋简体\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 85, 0);")
        self.lg_Button.setObjectName("lg_Button")
        self.ex_Button = QtWidgets.QPushButton(Form)
        self.ex_Button.setGeometry(QtCore.QRect(210, 220, 111, 41))
        self.ex_Button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 85, 0);\n"
"font: 12pt \"方正粗黑宋简体\";")
        self.ex_Button.setObjectName("ex_Button")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-9, -6, 411, 311))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/true.PNG"))
        self.label.setObjectName("label")
        self.label.raise_()
        self.na_Label.raise_()
        self.pw_Label.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lg_Button.raise_()
        self.ex_Button.raise_()

        self.retranslateUi(Form)
        #self.lg_Button.clicked.connect(Form.lg_ButtonClicked)
        #self.ex_Button.clicked.connect(Form.ex_ButtonClicked)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.na_Label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">用 户 名：</span></p></body></html>"))
        self.pw_Label.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:14pt; font-weight:600; text-decoration: underline;\">密   码：</span></p></body></html>"))
        self.lg_Button.setText(_translate("Form", "登陆"))
        self.ex_Button.setText(_translate("Form", "退出"))
import pic_rc
